/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.ijse.kembrose.view;

import com.sun.org.apache.xalan.internal.xsltc.compiler.Template;
import edu.ijse.kembrose.control.UserController;
import edu.ijse.kembrose.model.UserDetailsModel;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ruchira
 */
public class UserManage extends javax.swing.JFrame {

    /**
     * Creates new form UserManage
     */
    public UserManage() {
        initComponents();
        setTime();
        setDate();
        setLocationRelativeTo(null);
    }
    private void setTime() {
        new Thread() {
            @Override
            public void run() {
                while (true) {                    
                    Date date = new Date();
                    SimpleDateFormat dateFormat = new SimpleDateFormat("hh:mm:ss");
                    timelabel.setText(dateFormat.format(date));
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Template.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            
        }.start();
    }
   private void setDate() {
        java.util.Date date = new java.util.Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MMMM/yyyy");
        String formatedDate = dateFormat.format(date);
        datelabel.setText(formatedDate);
    }
   
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        timelabel = new javax.swing.JLabel();
        datelabel = new javax.swing.JLabel();
        piclabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        usernametext = new javax.swing.JTextField();
        passwordtext = new javax.swing.JTextField();
        priorityidtext = new javax.swing.JTextField();
        prioritynotext = new javax.swing.JTextField();
        emailtext = new javax.swing.JTextField();
        useridtext = new javax.swing.JTextField();
        deletebutton = new javax.swing.JButton();
        addbutton = new javax.swing.JButton();
        updatebutton = new javax.swing.JButton();
        searchbutton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 87, 43));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 650));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 87, 43));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(114, 114, 114));
        jLabel1.setText("User Manage");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(80, 0, 460, 57);

        timelabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        timelabel.setForeground(new java.awt.Color(114, 114, 114));
        timelabel.setText("12.00.00");
        jPanel2.add(timelabel);
        timelabel.setBounds(730, 30, 78, 25);

        datelabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        datelabel.setForeground(new java.awt.Color(114, 114, 114));
        datelabel.setText("20th April 2016");
        jPanel2.add(datelabel);
        datelabel.setBounds(730, 0, 100, 30);

        piclabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/kembrose/view/images/lunch.png"))); // NOI18N
        piclabel.setText("jLabel3");
        jPanel2.add(piclabel);
        piclabel.setBounds(10, 0, 60, 60);

        jPanel3.add(jPanel2);
        jPanel2.setBounds(0, 0, 900, 60);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setText("User Id  :");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(190, 120, 90, 30);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("Password  :");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(190, 220, 90, 30);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setText("Email  :");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(190, 390, 90, 30);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("User Name  :");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(190, 170, 90, 30);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setText("Priority Id  :");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(190, 270, 90, 30);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setText("Priority No  :");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(190, 330, 90, 30);

        usernametext.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        usernametext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usernametextKeyReleased(evt);
            }
        });
        jPanel3.add(usernametext);
        usernametext.setBounds(310, 170, 180, 24);

        passwordtext.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jPanel3.add(passwordtext);
        passwordtext.setBounds(310, 220, 180, 24);

        priorityidtext.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        priorityidtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priorityidtextActionPerformed(evt);
            }
        });
        priorityidtext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                priorityidtextKeyReleased(evt);
            }
        });
        jPanel3.add(priorityidtext);
        priorityidtext.setBounds(310, 270, 180, 24);

        prioritynotext.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        prioritynotext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                prioritynotextKeyReleased(evt);
            }
        });
        jPanel3.add(prioritynotext);
        prioritynotext.setBounds(310, 330, 180, 24);

        emailtext.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jPanel3.add(emailtext);
        emailtext.setBounds(310, 390, 180, 24);

        useridtext.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        useridtext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                useridtextKeyReleased(evt);
            }
        });
        jPanel3.add(useridtext);
        useridtext.setBounds(310, 120, 180, 24);

        deletebutton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        deletebutton.setText("Delete");
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });
        jPanel3.add(deletebutton);
        deletebutton.setBounds(700, 480, 120, 30);

        addbutton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        addbutton.setText("Add");
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });
        jPanel3.add(addbutton);
        addbutton.setBounds(280, 480, 120, 30);

        updatebutton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        updatebutton.setText("Update");
        updatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebuttonActionPerformed(evt);
            }
        });
        jPanel3.add(updatebutton);
        updatebutton.setBounds(420, 480, 120, 30);

        searchbutton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        searchbutton.setText("Search");
        jPanel3.add(searchbutton);
        searchbutton.setBounds(560, 480, 120, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/kembrose/view/images/FontAwesome_f015_64_4.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel8);
        jLabel8.setBounds(780, 90, 60, 60);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 10, 880, 630);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebuttonActionPerformed
        
    }//GEN-LAST:event_updatebuttonActionPerformed

    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed
//        String userId = useridtext.getText();
//        String userName = usernametext.getText();
//        String password = passwordtext.getText();
//        String priorityId = priorityidtext.getText();
//        //String prirityNo = prioritynotext.getText();
//        String email = emailtext.getText();
//        
//        UserDetailsModel userDetailsModel = new UserDetailsModel(userId, priorityId, userName, password, email);
//        boolean isAdded = UserController.addUser(userDetailsModel);
//        if (isAdded) {
//        JOptionPane.showMessageDialog(this, "Added Successful");
//        }else{
//        JOptionPane.showMessageDialog(this, "Added Not Successful");
//        }
        
        
        String userId = useridtext.getText();
        String userName = usernametext.getText();
        String userPassword = passwordtext.getText();
        String priorityId = priorityidtext.getText();
        Integer priorityNo = Integer.parseInt(prioritynotext.getText());
        String email = emailtext.getText();
        UserDetailsModel userDetailsModel = new UserDetailsModel(userId, priorityId, userName, userPassword, email);
        try {
            boolean isAdded=UserController.addUser(userDetailsModel);
            if(isAdded){
                JOptionPane.showMessageDialog(this, "Added Success...");
                addbutton.setVisible(false);
            }else{
            JOptionPane.showMessageDialog(this, "Added Failed...");
            }
        } catch (SQLException ex) {
            Logger.getLogger(UserManage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(UserManage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addbuttonActionPerformed

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
        String userId = useridtext.getText();
        try {
            boolean isDeleted=UserController.deleteUser(userId);
            if(isDeleted){
             JOptionPane.showMessageDialog(this, "Delete sucsess....");
            }else{
            JOptionPane.showMessageDialog(this, "Delete Failed....");
            }
        } catch (SQLException ex) {
            Logger.getLogger(UserManage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(UserManage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deletebuttonActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        new AdminHome().setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void usernametextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernametextKeyReleased
        String name = useridtext.getText();
        boolean matches = name.matches("[a-zA-Z[\\s]]*");
        if(!matches){
        usernametext.setText(name.substring(0, name.length() -1));
        }
    }//GEN-LAST:event_usernametextKeyReleased

    private void priorityidtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priorityidtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priorityidtextActionPerformed

    private void priorityidtextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priorityidtextKeyReleased
        String prId = priorityidtext.getText();
        boolean matches = prId.matches("[pr]{0,2}[\\d]{0,3}");
        if(!matches){
        priorityidtext.setText(prId.substring(0, prId.length() -1));
        }
    }//GEN-LAST:event_priorityidtextKeyReleased

    private void prioritynotextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prioritynotextKeyReleased
        String prNo = priorityidtext.getText();
        boolean matches = prNo.matches("[\\d]{0,2}");
        if(!matches){
        priorityidtext.setText(prNo.substring(0, prNo.length() -1));
        }
    }//GEN-LAST:event_prioritynotextKeyReleased

    private void useridtextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_useridtextKeyReleased
         String uId = useridtext.getText();
        boolean matches = uId.matches("[u]{0,1}[\\d]{0,3}");
        if(!matches){
        useridtext.setText(uId.substring(0, uId.length() -1));
        }
    }//GEN-LAST:event_useridtextKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserManage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbutton;
    private javax.swing.JLabel datelabel;
    private javax.swing.JButton deletebutton;
    private javax.swing.JTextField emailtext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField passwordtext;
    private javax.swing.JLabel piclabel;
    private javax.swing.JTextField priorityidtext;
    private javax.swing.JTextField prioritynotext;
    private javax.swing.JButton searchbutton;
    private javax.swing.JLabel timelabel;
    private javax.swing.JButton updatebutton;
    private javax.swing.JTextField useridtext;
    private javax.swing.JTextField usernametext;
    // End of variables declaration//GEN-END:variables
}
