/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.ijse.kembrose.view.subview;

import edu.ijse.kembrose.view.ItemCatagoryManage;

/**
 *
 * @author Ruchira
 */
public class ItemCatagoryManagePanel1 extends javax.swing.JPanel {

    public void setData() {
        Double lprice=Double.parseDouble(largetext.getText());
        Double mprice=Double.parseDouble(mediamtext.getText());
        Double sprice=Double.parseDouble(smalltext.getText());
        String size1="";
        if (largeCheck.isSelected()) {
        size1 = "Large";
        }else if (mediamcheck.isSelected()) {
        size1 = "Mediam";
        }else if (smallcheck.isSelected()) {
        size1 = "Small";
    }
        Integer personcount=Integer.parseInt(personcounttext.getText());
        ItemCatagoryManage icm1=new ItemCatagoryManage();
                icm1.setData(lprice,mprice,sprice,size1,personcount);
    }

    /**
     * Creates new form ItemCatagoryManagePanel1
     */
    public ItemCatagoryManagePanel1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        mediamcheck = new javax.swing.JCheckBox();
        smallcheck = new javax.swing.JCheckBox();
        largeCheck = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        mediamtext = new javax.swing.JTextField();
        personcounttext = new javax.swing.JTextField();
        largetext = new javax.swing.JTextField();
        smalltext = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("Available Sizes  :");
        jPanel5.add(jLabel3);
        jLabel3.setBounds(20, 10, 110, 30);

        mediamcheck.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        mediamcheck.setText("Mediam");
        jPanel5.add(mediamcheck);
        mediamcheck.setBounds(240, 10, 81, 23);

        smallcheck.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        smallcheck.setText("Small");
        jPanel5.add(smallcheck);
        smallcheck.setBounds(340, 10, 81, 23);

        largeCheck.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        largeCheck.setText("Large");
        jPanel5.add(largeCheck);
        largeCheck.setBounds(140, 10, 81, 23);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setText("Large ");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(110, 50, 110, 30);

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel8.setText("Person Count(Small)  :");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(20, 190, 150, 30);

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel12.setText("Mediam");
        jPanel5.add(jLabel12);
        jLabel12.setBounds(110, 90, 110, 30);

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel13.setText("Small");
        jPanel5.add(jLabel13);
        jLabel13.setBounds(110, 130, 110, 30);

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel14.setText("Prices  :");
        jPanel5.add(jLabel14);
        jLabel14.setBounds(20, 50, 110, 30);

        mediamtext.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        mediamtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediamtextActionPerformed(evt);
            }
        });
        jPanel5.add(mediamtext);
        mediamtext.setBounds(180, 90, 160, 24);

        personcounttext.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jPanel5.add(personcounttext);
        personcounttext.setBounds(180, 190, 160, 24);

        largetext.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jPanel5.add(largetext);
        largetext.setBounds(180, 50, 160, 24);

        smalltext.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jPanel5.add(smalltext);
        smalltext.setBounds(180, 130, 160, 24);

        add(jPanel5);
        jPanel5.setBounds(0, 0, 420, 240);
    }// </editor-fold>//GEN-END:initComponents

    private void mediamtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediamtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mediamtextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JCheckBox largeCheck;
    private javax.swing.JTextField largetext;
    private javax.swing.JCheckBox mediamcheck;
    private javax.swing.JTextField mediamtext;
    private javax.swing.JTextField personcounttext;
    private javax.swing.JCheckBox smallcheck;
    private javax.swing.JTextField smalltext;
    // End of variables declaration//GEN-END:variables
}
