/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.ijse.kembrose.view.subview;

import edu.ijse.kembrose.view.ItemCatagoryManage;

/**
 *
 * @author Ruchira
 */
public class ItemCatagoryManagePanel2 extends javax.swing.JPanel {
   
    public void setData(){
    String size2=size2text.getText();
    Double price=Double.parseDouble(pricetext.getText());
    Integer personcount=Integer.parseInt(personcounttext.getText());
    ItemCatagoryManage icm2=new ItemCatagoryManage();
    icm2.setData(size2,price,personcount);
    
    }
    /**
     * Creates new form ItemCatagoryManagePanel2
     */
    public ItemCatagoryManagePanel2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        personcounttext = new javax.swing.JTextField();
        size2text = new javax.swing.JTextField();
        pricetext = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(420, 240));
        setLayout(null);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setText("Available Size  :");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(20, 10, 110, 30);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setText("Person Count  :");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(20, 100, 150, 30);

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel11.setText("Price  :");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(20, 50, 110, 30);

        personcounttext.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jPanel4.add(personcounttext);
        personcounttext.setBounds(180, 100, 160, 24);

        size2text.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jPanel4.add(size2text);
        size2text.setBounds(180, 10, 160, 24);

        pricetext.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jPanel4.add(pricetext);
        pricetext.setBounds(180, 50, 160, 24);

        add(jPanel4);
        jPanel4.setBounds(0, 0, 420, 240);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField personcounttext;
    private javax.swing.JTextField pricetext;
    private javax.swing.JTextField size2text;
    // End of variables declaration//GEN-END:variables

}
